package https.dhl24_com_pl.webapi2.provider.service_html_ws_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-05-15T22:32:37.978+02:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "DHL24WebapiService",
                  wsdlLocation = "https://dhl24.com.pl/webapi2",
                  targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1")
public class DHL24WebapiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://dhl24.com.pl/webapi2/provider/service.html?ws=1", "DHL24WebapiService");
    public final static QName DHL24WebapiPort = new QName("https://dhl24.com.pl/webapi2/provider/service.html?ws=1", "DHL24WebapiPort");
    static {
        URL url = null;
        try {
            url = new URL("https://dhl24.com.pl/webapi2");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DHL24WebapiService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://dhl24.com.pl/webapi2");
        }
        WSDL_LOCATION = url;
    }

    public DHL24WebapiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DHL24WebapiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DHL24WebapiService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DHL24WebapiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DHL24WebapiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DHL24WebapiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DHL24WebapiPort
     */
    @WebEndpoint(name = "DHL24WebapiPort")
    public DHL24WebapiPort getDHL24WebapiPort() {
        return super.getPort(DHL24WebapiPort, DHL24WebapiPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DHL24WebapiPort
     */
    @WebEndpoint(name = "DHL24WebapiPort")
    public DHL24WebapiPort getDHL24WebapiPort(WebServiceFeature... features) {
        return super.getPort(DHL24WebapiPort, DHL24WebapiPort.class, features);
    }

}
