package https.dhl24_com_pl.webapi2.provider.service_html_ws_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-05-15T22:32:37.826+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", name = "DHL24WebapiPort")
@XmlSeeAlso({https.dhl24_com_pl.webapi2.provider.service.ObjectFactory.class})
public interface DHL24WebapiPort {

    /**
     * Anulowanie zamówionego kuriera
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#cancelCourierBooking")
    @RequestWrapper(localName = "cancelCourierBooking", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CancelCourierBooking")
    @ResponseWrapper(localName = "cancelCourierBookingResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CancelCourierBookingResponse")
    @WebResult(name = "cancelCourierBookingResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfDeletenotification cancelCourierBooking(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "orders", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfString orders
    );

    /**
     * Zamawianie kuriera
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#bookCourier")
    @RequestWrapper(localName = "bookCourier", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.BookCourier")
    @ResponseWrapper(localName = "bookCourierResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.BookCourierResponse")
    @WebResult(name = "bookCourierResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfString bookCourier(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "pickupDate", targetNamespace = "")
        java.lang.String pickupDate,
        @WebParam(name = "pickupTimeFrom", targetNamespace = "")
        java.lang.String pickupTimeFrom,
        @WebParam(name = "pickupTimeTo", targetNamespace = "")
        java.lang.String pickupTimeTo,
        @WebParam(name = "additionalInfo", targetNamespace = "")
        java.lang.String additionalInfo,
        @WebParam(name = "shipmentIdList", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfString shipmentIdList,
        @WebParam(name = "shipmentOrderInfo", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ShipmentOrderInfo shipmentOrderInfo,
        @WebParam(name = "courierWithLabel", targetNamespace = "")
        java.lang.Boolean courierWithLabel
    );

    /**
     * Usuwanie przesyłek w systemie DHL
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#deleteShipments")
    @RequestWrapper(localName = "deleteShipments", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.DeleteShipments")
    @ResponseWrapper(localName = "deleteShipmentsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.DeleteShipmentsResponse")
    @WebResult(name = "deleteShipmentsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfDeletenotification deleteShipments(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipments", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfString shipments
    );

    /**
     * Definiowanie przesyłek w systemie DHL
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#createShipments")
    @RequestWrapper(localName = "createShipments", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CreateShipments")
    @ResponseWrapper(localName = "createShipmentsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CreateShipmentsResponse")
    @WebResult(name = "createShipmentsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfShipmentbasicdata createShipments(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipments", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfShipmentfulldata shipments
    );

    /**
     * Usuwanie przesyłki w systemie DHL - metoda agregująca
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#deleteShipment")
    @RequestWrapper(localName = "deleteShipment", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.DeleteShipment")
    @ResponseWrapper(localName = "deleteShipmentResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.DeleteShipmentResponse")
    @WebResult(name = "deleteShipmentResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.DeleteShipmentResponse2 deleteShipment(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipment", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.DeleteShipmentRequest shipment
    );

    /**
     * Pobieranie najbliższych punktów serwisowych typu Last Mile bez COD
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getNearestServicepoints")
    @RequestWrapper(localName = "getNearestServicepoints", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetNearestServicepoints")
    @ResponseWrapper(localName = "getNearestServicepointsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetNearestServicepointsResponse")
    @WebResult(name = "getNearestServicepointsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.GetNearestServicepointsResponse2 getNearestServicepoints(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "structure", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.GetNearestServicepointsRequest structure
    );

    /**
     * Pobranie różnego rodzaju etykiet związanych z przesyłkami.
     * Za jednym wywołaniem można pobrać maksymalnie 3 etykiety
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getLabels")
    @RequestWrapper(localName = "getLabels", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetLabels")
    @ResponseWrapper(localName = "getLabelsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetLabelsResponse")
    @WebResult(name = "getLabelsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfItemtoprintresponse getLabels(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "itemsToPrint", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfItemtoprint itemsToPrint
    );

    /**
     * Pobranie raportu Potwierdzenie Nadanych Przesyłek (PNP)
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getPnp")
    @RequestWrapper(localName = "getPnp", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetPnp")
    @ResponseWrapper(localName = "getPnpResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetPnpResponse")
    @WebResult(name = "getPnpResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.PnpResponse getPnp(

        @WebParam(name = "pnpRequest", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.PnpRequest pnpRequest
    );

    /**
     * Pobieranie informacji o możliwościach przesyłek międzynarodowych
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getReturnParams")
    @RequestWrapper(localName = "getReturnParams", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetReturnParams")
    @ResponseWrapper(localName = "getReturnParamsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetReturnParamsResponse")
    @WebResult(name = "getReturnParamsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.GetReturnParamsResponse2 getReturnParams(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData
    );

    /**
     * Pobieranie podstawowych danych o ilości przesyłek
     * Maksymalny zakres dat to 90 dni.
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getMyShipmentsCount")
    @RequestWrapper(localName = "getMyShipmentsCount", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetMyShipmentsCount")
    @ResponseWrapper(localName = "getMyShipmentsCountResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetMyShipmentsCountResponse")
    @WebResult(name = "getMyShipmentsCountResult", targetNamespace = "")
    public int getMyShipmentsCount(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "createdFrom", targetNamespace = "")
        java.lang.String createdFrom,
        @WebParam(name = "createdTo", targetNamespace = "")
        java.lang.String createdTo
    );

    /**
     * Weryfikacja poprawności kodu pocztowego oraz pobranie dostępnych
     * w danej chwili usług przewozowych.
     * Odpowiedź metody jest funkcją godziny, w jakiej przychodzi żądanie (usługi terminowe
     * są dostępne do ustalonych godzin).
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getPostalCodeServices")
    @RequestWrapper(localName = "getPostalCodeServices", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetPostalCodeServices")
    @ResponseWrapper(localName = "getPostalCodeServicesResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetPostalCodeServicesResponse")
    @WebResult(name = "getPostalCodeServicesResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.PostalCodeServicesResponse getPostalCodeServices(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "postCode", targetNamespace = "")
        java.lang.String postCode,
        @WebParam(name = "pickupDate", targetNamespace = "")
        java.lang.String pickupDate
    );

    /**
     * Pobieranie informacji o przesyłkach
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getLabelsData")
    @RequestWrapper(localName = "getLabelsData", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetLabelsData")
    @ResponseWrapper(localName = "getLabelsDataResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetLabelsDataResponse")
    @WebResult(name = "getLabelsDataResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfItemtolabeldataresponse getLabelsData(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "itemsToLabelData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfItemtolabeldata itemsToLabelData
    );

    /**
     * Pobieranie skanów LP w systemie DHL
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getShipmentScan")
    @RequestWrapper(localName = "getShipmentScan", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetShipmentScan")
    @ResponseWrapper(localName = "getShipmentScanResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetShipmentScanResponse")
    @WebResult(name = "getShipmentScanResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ScanToPrintResponse getShipmentScan(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipmentId", targetNamespace = "")
        java.lang.String shipmentId
    );

    /**
     * Sprawdzenie wersji webapi.
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getVersion")
    @RequestWrapper(localName = "getVersion", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetVersionResponse")
    @WebResult(name = "getVersionResult", targetNamespace = "")
    public java.lang.String getVersion()
;

    /**
     * Definiowanie przesyłki w systemie DHL - metoda agregująca
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#createShipment")
    @RequestWrapper(localName = "createShipment", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CreateShipment")
    @ResponseWrapper(localName = "createShipmentResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CreateShipmentResponse")
    @WebResult(name = "createShipmentResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.CreateShipmentResponse2 createShipment(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipment", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.CreateShipmentRequest shipment
    );

    /**
     * Zwrot danych
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getReturnByWaybill")
    @RequestWrapper(localName = "getReturnByWaybill", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetReturnByWaybill")
    @ResponseWrapper(localName = "getReturnByWaybillResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetReturnByWaybillResponse")
    @WebResult(name = "getReturnByWaybillResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfCreateshipmentresponse getReturnByWaybill(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "itemsToPrint", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.ArrayOfReturnitemtoprint itemsToPrint
    );

    /**
     * Stwórz przesyłkę zwrotną
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#createShipmentReturn")
    @RequestWrapper(localName = "createShipmentReturn", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CreateShipmentReturn")
    @ResponseWrapper(localName = "createShipmentReturnResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.CreateShipmentReturnResponse")
    @WebResult(name = "createShipmentReturnResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfCreatereturnshipmentresponse createShipmentReturn(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipment", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.CreateReturnShipmentRequest shipment
    );

    /**
     * Pobieranie informacji o możliwościach przesyłek międzynarodowych
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getInternationalParams")
    @RequestWrapper(localName = "getInternationalParams", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetInternationalParams")
    @ResponseWrapper(localName = "getInternationalParamsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetInternationalParamsResponse")
    @WebResult(name = "getInternationalParamsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.GetInternationalParamsResponse2 getInternationalParams(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData
    );

    /**
     * Pobieranie podstawowych danych o przesyłkach
     * Maksymalny zakres dat to 90 dni. Zwracane jest maksimum 100 przesyłek, jeśli jest ich więcej należy korzystać z offsetu.
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getMyShipments")
    @RequestWrapper(localName = "getMyShipments", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetMyShipments")
    @ResponseWrapper(localName = "getMyShipmentsResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetMyShipmentsResponse")
    @WebResult(name = "getMyShipmentsResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.ArrayOfShipmentbasicdata getMyShipments(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "createdFrom", targetNamespace = "")
        java.lang.String createdFrom,
        @WebParam(name = "createdTo", targetNamespace = "")
        java.lang.String createdTo,
        @WebParam(name = "offset", targetNamespace = "")
        java.lang.Integer offset
    );

    /**
     * Pobranie danych na temat zdarzeń związanych z przesyłką o przekazanym identyfikatorze.
     */
    @WebMethod(action = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1#getTrackAndTraceInfo")
    @RequestWrapper(localName = "getTrackAndTraceInfo", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetTrackAndTraceInfo")
    @ResponseWrapper(localName = "getTrackAndTraceInfoResponse", targetNamespace = "https://dhl24.com.pl/webapi2/provider/service.html?ws=1", className = "https.dhl24_com_pl.webapi2.provider.service.GetTrackAndTraceInfoResponse")
    @WebResult(name = "getTrackAndTraceInfoResult", targetNamespace = "")
    public https.dhl24_com_pl.webapi2.provider.service.TrackAndTraceResponse getTrackAndTraceInfo(

        @WebParam(name = "authData", targetNamespace = "")
        https.dhl24_com_pl.webapi2.provider.service.AuthData authData,
        @WebParam(name = "shipmentId", targetNamespace = "")
        java.lang.String shipmentId
    );
}
